### ISSUE TITLE
Tkinter import error

### ISSUE THREAD

**Issue by alfredo87** [inxi/guanxi#1]
When running the script in Fedora 21 and having installed all the necessary TkInter and Tk I get this error message:
Traceback (most recent call last):
  File "./gui.py", line 20, in <module>
    from inxiLib import buttonPanel, interface
  File "/home/fred/Downloads/guanxi-master/inxiLib/**init**.py", line 1, in <module>
    from .buttonPanel import *
  File "/home/fred/Downloads/guanxi-master/inxiLib/buttonPanel.py", line 2, in <module>
    from tkinter import *
ImportError: No module named tkinter
The installation output is:
Installed:
  tkinter.x86_64 0:2.7.8-9.fc21                                                 

Dependency Installed:
  tix.x86_64 1:8.4.3-15.fc21              tk.x86_64 1:8.6.3-1.fc21

**Comment by trash-80** [comment]
For some reason, I was never notified about this issue, but since this project is quite old and needs lots of updating, I'm closing this issue.
